
# base
#  from: http://lorisleiva.com/laravel-deployment-using-gitlab-pipelines/
#  and: https://github.com/edbizarro/gitlab-ci-pipeline-php
#  and: gitlab docs

image: edbizarro/gitlab-ci-pipeline-php:7.1-alpine

variables:
    MYSQL_ROOT_PASSWORD: secret # needed by service
    MYSQL_DATABASE: homestead_test # depends on what is set in phpunit.xml
    MYSQL_USER: homestead # depends on what is set in .env.example
    MYSQL_PASSWORD: secret # depends on what is set in .env.example
    DB_DATABASE: homestead_test # override default .env.example value
    DB_HOST: mysql # docker service hostname.

before_script:
    - composer config cache-files-dir cache-composer
    - cp .env.example .env

stages:
    - test

cache:
    # The variable CI_COMMIT_REF_SLUG
    # refers to the slug of the branch.
    # For example: `master` for the master branch.
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - cache-composer
        - vendor/

.ci-runner: &ci-runner
    tags:
        - web # limit runner to "docker" executor for web

test:
    <<: *ci-runner
    stage: test
    services:
        - mariadb:10.2
    script:
        - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
        - php artisan key:generate
        - vendor/bin/phpunit -v --colors=never --stderr --stop-on-error --stop-on-failure
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /DOCS|NO-TEST/
